[theme]  
primaryColor = "#3e8ef7"  # Coinbase vibrant blue  
backgroundColor = "#ffffff"  # Clean white background  
secondaryBackgroundColor = "#f3f4f6"  # Light gray for contrast  
textColor = "#333333"  # Dark gray for readability  
font = "sans serif"