[theme]
primaryColor = "#1652F0"    # Coinbase blue for primary actions
backgroundColor = "#0A0E17" # Deep navy background
secondaryBackgroundColor = "#1D2633" # Card surfaces
textColor = "#FFFFFF"       # White primary text
font = "sans serif"         # Will implement Inter via CSS later